stages:
  - setup
  - pages

setup:
  stage: setup
  image: "node:alpine"
  script:
    - npm install
  artifacts:
    paths:
      - node_modules

pages:
  stage: pages
  image: envimate/hugo:latest
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - hugo
  artifacts:
    paths:
      - public
  only:
    - main
