baseURL = "https://jan-kohlbach.gitlab.io/boilerplates/hugo"
relativeURLs = true
languageCode = "en"
title = "boilerplate-hugo"
disableKinds = ["taxonomy", "term"]

[params]
  themeColor = "#000000"
  description = "lorem ipsum"
